name: bluetooth_enable
description: Flutter plugin to turn on bluetooth within app (Android only)
version: 0.1.3
# authors: 
#   - Hui
homepage: https://github.com/huitingyeong/bluetooth_enable

environment:
  sdk: ">=2.17.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.hui.bluetooth_enable
    pluginClass: BluetoothEnablePlugin
